package mongodb;

public class TEXTBANK {
	public final static String _ID = "_id";
	public final static String _SENDER = "sender";
	public final static String _RECIPIENTS = "recipients";
	public final static String _CC = "cc";
	public final static String _TEXT = "text";
	public final static String _MID = "mid";
	public final static String _FPATH = "fpath";
	public final static String _BCC = "bcc";
	public final static String _TO = "to";
	public final static String _REPLYTO = "replyto";
	public final static String _CTYPE = "ctype";
	public final static String _FNAME = "fname";
	public final static String _DATE = "date";
	public final static String _FOLDER = "folder";
	public final static String _SUBJECT = "subject";
	public final static String DBNAME = "email";
	public final static String COLLECTION = "messages";
	public final static String LOCALHOST = "localhost"; 
	public final static int PORT = 27017; 
	public final static String SHOWBUTTON = "Show";
	public final static String UPDATEBUTTON = "Move";
	public final static String DELETEBUTTON = "Delete";
	public final static String SEARCH_BY_TEXT_BUTTON = "Search By Text";
	public final static String SEARCH_BY_SENDER_BUTTON = "Search By Sender";
	public final static String UPDATESTATUS_SUCCESS = "Mail(s) moved";
	public final static String UPDATESTATUS_FAILURE = "Mail(s) can only be moved to a different folder";
	public final static String DELETESTATUS = " Mail(s) are deleted";
	public final static String NO_MAILS_SELECTED = "Please select mails to perform Move/Delete operation";
	public final static String NO_FOLDER_SELECTED = "Please select a folder to display the mails";
	public final static String NO_TEXT_ENTERED_SBT = "Please enter text to be searched by text";
	public final static String NO_TEXT_ENTERED_SBS = "Please enter text to be searched by sender";
	public final static String  SEARCH_SUCCESS = "Search successful";
	//public final static String UPDATESTATUS = "Moved the mail(s) to the folder";
	public static final String CTYPEVAL = "text/plain; charset=ANSI_X3.4-1968";
	public static final String MIDVAL = "8232360.10758608412345.JavaMail";
	public static final String QUERY1 = "Count All Mails";
	public static final String QUERY2 = "Count Mails Folder-wise";
	public static final String QUERY3 = "Query-3";
	public static final Object QUERY1_MSG  = "Total Number of mail(s) in the entire database are ";
	public static final Object QUERY2_MSG_ERROR = "Folder name is required for to execute this Query, select folder name";
	public static final Object QUERY2_MSG  = "Total number of mail(s) in the folder ";
	public static final Object SORT_DESC = "Sort Mails by Date-Descending";
	public static final Object SORT_ASC = "Sort Mails by Date- Ascending";
	public static final Object SORT_SUCCESS_ASC = "Sorted the mails in Ascending order";
	public static final Object SORT_SUCCESS_DESC = "Sorted the mails in Descending order";
}
